### ISSUE TITLE
JEG 3.2.3 on K3s v1.28.5 unable to start kernels. 3.2.2 pyspark worked.

### ISSUE THREAD

**Issue by paf91** [jupyter-server/enterprise_gateway#1379]
## Description
Whenever I start kernel based on kubernetes I'm getting this error on version 3.2.3:

Error Starting Kernel
HTTP 500: Internal Server Error (Error from Gateway: [Error occurred creating role binding for namespace 'guest-fab3e59b-edbb-4e1d-912e-087b1798425b': module 'kubernetes.client' has no attribute 'V1Subject'] Error occurred creating role binding for namespace 'guest-fab3e59b-edbb-4e1d-912e-087b1798425b': module 'kubernetes.client' has no attribute 'V1Subject'. Ensure gateway url is valid and the Gateway instance is running.)

## Reproduce

values.yaml:

```yaml
service:
  type: "LoadBalancer"
  # Master public IP on which to expose EG.
  k8sMasterPublicIP: '<redacted, private ip like 10.x.x.x>'
  ports:
    - name: "http"
      port: 8888
      targetPort: 8888
    - name: "http-response"
      port: 8877
      targetPort: 8877
ingress:
  enabled: false
kernel:
  shareGatewayNamespace: false
  allowedKernels:
    - r_kubernetes
    - python_kubernetes
    - python_tf_kubernetes
    - python_tf_gpu_kubernetes
    - scala_kubernetes
    - spark_r_kubernetes
    - spark_python_kubernetes
    - spark_scala_kubernetes
    - spark_python_operator
    - python3
  defaultKernelName: python_kubernetes
kip:
  enabled: true
  serviceAccountName: 'kernel-image-puller-sa'
  criSocket: /run/containerd/containerd.sock
```

`helm  upgrade --install  enterprise-gateway   https://github.com/jupyter-server/enterprise_gateway/releases/download/v3.2.3/jupyter_enterprise_gateway_helm-3.2.3.tar.gz    --namespace enterprise-gateway    -f ~/jupyter/gateway/values-balancer.yaml`

kubectl get pods -n enterprise-gateway:
![image](https://github.com/jupyter-server/enterprise_gateway/assets/12195041/2e430911-d37a-4d3f-b5f3-da4f73c5ae5d)

curl -X POST -i 'http://<redacted_private_ip>:8888/api/kernels' --data '{ "name": "spark_python_kubernetes", "env": { "KERNEL_USERNAME": "jovyan" }}'

HTTP/1.1 500 Error occurred creating role binding for namespace 'jovyan-99878812-28c5-49ad-8cbc-cb81713e7ba3': module 'kubernetes.client' has no attribute 'V1Subject'
Server: TornadoServer/6.2
Content-Type: application/json
Date: Tue, 02 Apr 2024 23:17:01 GMT
X-Content-Type-Options: nosniff
Content-Length: 182

{"reason": "Error occurred creating role binding for namespace 'jovyan-99878812-28c5-49ad-8cbc-cb81713e7ba3': module 'kubernetes.client' has no attribute 'V1Subject'", "message": ""}

## Expected behavior

Kernel starts

## Context

JEG 3.2.3 on K3s v1.28.5
